env:
  browser: true
  jasmine: true
extends: 'eslint:recommended'
globals:
  Sb: readonly
parserOptions:
  ecmaVersion: 5
rules:
  indent: [2, 2]
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
