language: node_js
dist: trusty
node_js:
  - node
addons:
  apt:
    packages:
      - firefox
os: linux
cache: yarn

script:
  - echo 'Testing'
  - yarn run test
  - echo 'Building dist files'
  - mkdir dist
  - yarn run build
  - echo 'Building documentation'
  - yarn run build:docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true